before_script:
  - apt-get update -qy
  - apt-get install -qy locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

test:
  script:
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python sand_server.py run --port 5000 &
  - cd tests/ && pip install -r requirements.txt
  - python run.py -v
  artifacts:
    paths:
    - tests/report.log
    - tests/server.log

production:
  type: deploy
  script:
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=sand-conf-server --api-key=$HEROKU_PRODUCTION_API_KEY
