language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - python sand_server.py run --port 5000 &
  - cd tests/
  - pip install -r requirements.txt
  - python run.py -v

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: sand-conf-server
